### ISSUE TITLE
Unknown option: .name

### ISSUE THREAD

**Issue by imparth7** [oktaysenkan/react-native-iconify#13]
Unknown option: .name. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

This error shows me when I install react-native-iconify in my new Project.

expo: ~50.0.6,
react: 18.2.0,
react-native: 0.73.4

**Comment by oktaysenkan** [comment]
Can you share package.json and babelrc.js?

**Comment by imparth7** [comment]
babel.config.js

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      "nativewind/babel",
      'react-native-iconify/plugin',
    ],
  };
};


package.json

{
  "name": "newapp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-navigation/bottom-tabs": "^6.5.12",
    "@react-navigation/native": "^6.1.10",
    "@types/react": "~18.2.45",
    "expo": "~50.0.6",
    "expo-status-bar": "~1.11.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.73.4",
    "react-native-iconify": "^1.0.0",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-svg": "14.1.0",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
