### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ArterumMC** [oktaysenkan/react-native-iconify#17]
![Screenshot_20240320_092402](https://github.com/oktaysenkan/react-native-iconify/assets/162975102/1505d3e5-0355-46e4-9313-67d244cfceed)

Hi there,

I've encountered a bug while using react-native-iconify that I haven't encountered before. Despite checking online and in library issues, I couldn't find anyone else experiencing the same problem.

I'm using Expo SDK 50 on a --dev client. Here's my package.json:

```
 "expo": "~50.0.13",
 "expo-dev-client": "^3.3.10",
 "react": "18.2.0",
 "react-native": "0.73.5",
 "react-native-iconify": "^1.0.0",
```
 
 
In my babel plugin configuration, I have:
 
```
 module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
    'react-native-reanimated/plugin',
    'react-native-iconify/plugin'
    ]
  };
};
```

Here's how I import and use Iconify in my component:

At the top of my component:
`import { Iconify } from 'react-native-iconify';`

In the render method:
`<Iconify icon="iconamoon:discount-fill" color="#fff" />`

If anyone has a solution or tips to resolve this issue, I'd appreciate it.

**Comment by dereckquock** [comment]
We've run into this issue as well. It seems like some icons aren't found for some reason 🤷‍♂️

**Comment by oktaysenkan** [comment]
Thank you for contribution. It works well in example app on Expo 50.
Can you share repository and update to v1.0.1?

![simulator_screenshot_917E2B85-FDC9-489F-B59D-250161057F45](https://github.com/oktaysenkan/react-native-iconify/assets/42527467/68aaa5c5-8e76-4e3a-9399-baf7cac75d12)
