### ISSUE TITLE
Exception thrown while executing UI block: -[__NSDictionaryM firstObject]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by pjaymedina** [oktaysenkan/react-native-iconify#2]
Exception thrown while executing UI block: -[__NSDictionaryM firstObject]: unrecognized selector sent to instance 0x6000024c9f20  __53-[ABI46_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke     ABI46_0_0RCTUIManager.m:1202 __53-[ABI46_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.431 _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_drain _dispatch_main_queue_callback_4CF __CFRUNLOOP_IS_SERV

 "react-native-svg": "12.3.0"
 "react-native": "0.69.9",
"react": "18.0.0",
"expo": "^46.0.0",

**Comment by oktaysenkan** [comment]
Can you share repo? I think its related to react-native-svg.

**Comment by oktaysenkan** [comment]
Fixed on **[v0.2.9](https://github.com/oktaysenkan/react-native-iconify/releases/tag/v0.2.9)**

**Comment by oktaysenkan** [comment]
Update react-native-svg version to 13.x
