### ISSUE TITLE
Was the icon prop unintentionally made compulsory in 1.0.0?

### ISSUE THREAD

**Issue by nathantew14** [oktaysenkan/react-native-iconify#20]
<img width="1170" alt="Screenshot 2024-06-24 at 10 37 19 PM" src="https://github.com/oktaysenkan/react-native-iconify/assets/40333518/bf9949cf-02b2-4197-83bf-cf8cd16dd711">

The default value of 24 was removed here but the typescript for Props still indicates size as optional. Can we add the default value back?

**Comment by oktaysenkan** [comment]
I will take care of it

**Comment by oktaysenkan** [comment]
Fixed!
