### ISSUE TITLE
Support for spinning icons

### ISSUE THREAD

**Issue by ubaidvalere** [oktaysenkan/react-native-iconify#21]
When using spinning icons, it does not animate. It is visible as static only.

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/7c56b8b3-56fb-45bb-9a8f-07eb2cc2cf45">

**Comment by oktaysenkan** [comment]
i think it is not possible, you can open issue in **[react-native-svg](https://github.com/software-mansion/react-native-svg)** repository.
