### ISSUE TITLE
Error installing babel plugin

### ISSUE THREAD

**Issue by HASH-0021** [oktaysenkan/react-native-iconify#22]
I have followed the steps for installing the library. But I am getting error ```Error: Iconify: You need to install a Babel plugin before using this library. You can continue by adding the following to your babel.config.js``` while using any icons in the code.

Below are the files overview for reference.

```
package.json file

"dependencies": {
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-iconify": "^1.0.2",
    "react-native-svg": "^15.4.0"
  },
"devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.85",
    "@react-native/eslint-config": "0.74.85",
    "@react-native/metro-config": "0.74.85",
    "@react-native/typescript-config": "0.74.85",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
```

```
babel.config.js file

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-iconify/plugin'],
};
```

**Comment by HASH-0021** [comment]
```<Iconify icon="mdi:heart" size={24} color="#900" />``` line is causing this issue. More specifically, the color prop having ```#900``` value. By changing the value to valid color value, the issue is no longer present. Please fix the issue occurring while giving this color prop value.

**Comment by oktaysenkan** [comment]
https://github.com/oktaysenkan/react-native-iconify?tab=readme-ov-file#iconify-you-need-to-install-a-babel-plugin-before-using-this-library-you-can-continue-by-adding-the-following-to-your-babelconfigjs
