### ISSUE TITLE
Update react-native-svg peerDependencies

### ISSUE THREAD

**Issue by vieraleonel** [oktaysenkan/react-native-iconify#24]
Hi, first of all, excellent package!

I'm writing to ask if react-native-svg can be changed to `react-native-svg@^13.2.0` in order to avoid conflicts with default expo versions (SDK 51 uses `react-native-svg@15.2.0`) and this gives an error with dep resolving.

This can be resolved with `--force or --legacy-peer-deps` but i think it would be a lot nicer if this is avoided.

If you are interested I can make a PR and that version/change seems correct for you.

PD: sorry for the first report of this issue. I press enter early by error

**Comment by oktaysenkan** [comment]
Hello, it's my fault, you can fix it :)
