### ISSUE TITLE
Babel plugin

### ISSUE THREAD

**Issue by pee0803** [oktaysenkan/react-native-iconify#5]
Hi there,

I am first try to use iconify in react native.
I have followed the steps provided in Readme.md to add the plugin in babel.config.js, and clear cache for my project.
But it turns out an error like the image below.

![Simulator Screenshot - iPhone 14 Pro - 2023-09-21 at 15 07 48](https://github.com/oktaysenkan/react-native-iconify/assets/72015683/3ac89bb6-a955-4b61-b6f3-7d4782110259)

![Screenshot 2023-09-21 at 15 11 37](https://github.com/oktaysenkan/react-native-iconify/assets/72015683/d3abeee7-9c70-4c26-ae1a-edb9f8539deb)

I would like to humbly seek your advice to resolve this issue.
Thanks in advance.

**Comment by oktaysenkan** [comment]
Check your **presets** and **plugins** properties **babel.config.js**. What is **env.production.plugins** ?

```ts
module.exports = {
  presets: [
    ...
  ],
  plugins: [
    ...
    'react-native-iconify/plugin',
  ],
};
```

**Comment by pee0803** [comment]
I have figured out and the this issue is fixed. Thank you very much.
