### ISSUE TITLE
 Unable to resolve "@iconify/utils" from "node_modules\react-native-iconify\src\Iconify.tsx"

### ISSUE THREAD

**Issue by Jaysalasi** [oktaysenkan/react-native-iconify#7]
after installing npm install react-native-iconify
Unable to resolve "@iconify/utils" from "node_modules\react-native-iconify\src\Iconify.tsx"

![image](https://github.com/oktaysenkan/react-native-iconify/assets/46465079/8831ebd4-064b-4056-848e-2fd70573b69c)

**Comment by oktaysenkan** [comment]
Did you try remove node_modules?

Can you share these informations?
- Node version
- OS Version
- npm / yarn version
- package.json

**Comment by Jaysalasi** [comment]
Node version: 18.16.0
OS: windows 10
npm: 9.5.1

package.json
{
  "name": "digiyo",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/bottom-tabs": "^6.5.9",
    "@react-navigation/drawer": "^6.6.4",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "apisauce": "^3.0.1",
    "expo": "~49.0.12",
    "expo-av": "~13.4.1",
    "expo-camera": "~13.4.4",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-media-library": "~15.4.1",
    "expo-sharing": "~11.5.0",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-native-event-listeners": "^1.0.7",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-iconify": "^0.2.10",
    "react-native-paper": "^5.10.6",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^6.0.0-alpha.8"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "react-native-svg-transformer": "^1.1.0"
  },
  "private": true
}

**Comment by shadab14meb346** [comment]
any updates on this? I am also facing the same error

**Comment by oktaysenkan** [comment]
Can you try this? add **mjs** and **cjs** to **resolver.sourceExts** in **metro.config.js**

```ts
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  resolver: {
    sourceExts: [...defaultConfig.resolver.sourceExts, 'mjs', 'cjs'],
  },
};

module.exports = mergeConfig(defaultConfig, config);

```

**Comment by shadab14meb346** [comment]
Hey @oktaysenkan your comment did help me. thanks.

Here's how I did solve it for my React Native project with Metro, babel and `metro-react-native-babel-preset` package.

My earlier `babel.config.js` looked like below

```javascript
module.exports = {
   presets: ['module:metro-react-native-babel-preset'],
   plugins: ['react-native-reanimated/plugin'],
 };
```

Earlier `metro.config.js`

```javascript

/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

After the Fix `metro.config.js`

```javascript
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    sourceExts: ['js', 'json', 'ts', 'tsx', 'jsx', 'cjs'], // Add other extensions if needed
  },
};

```

After the fix `babel.config.js`
```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin', 'react-native-iconify/plugin'],
};
```
