### ISSUE TITLE
`Element type is invalid: expected ... but got: undefined`

### ISSUE THREAD

**Issue by MAXOUXAX** [oktaysenkan/react-native-iconify#8]
Hi, I just installed this library on a fresh Expo 50 project using the Metro Bundler for web, and when trying to use the `Iconify` component, I get this error:

```
Uncaught Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Iconify`.
```

## Environment

Node: `v20.10.0`
Expo: `v50.0.2`
react-native-iconify: `v0.2.11`
Web bundler: `Metro`

## Reproduction

[Here's a minimal reproduction GitHub repository](https://github.com/MAXOUXAX/iconify-reproduction)

**Comment by oktaysenkan** [comment]
Thanks for the contribution.
I have never tested it on the web. I will fix this soon.

**Comment by oktaysenkan** [comment]
react-native-web support is added on [v1.0.0 ](https://github.com/oktaysenkan/react-native-iconify/releases/tag/v1.0.0) 🥳🎉
