### ISSUE TITLE
Flowbite iconset not supported

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [oktaysenkan/react-native-iconify#9]
Hi, thank you for the great library, I am using it as replacement for `react-native-vector-icons`. However, it seems that [Flowbite iconset](https://icon-sets.iconify.design/flowbite/) is not available yet, for now :)

**Comment by oktaysenkan** [comment]
Thanks for the contribution :).
New icons are available on [v0.2.12](https://github.com/oktaysenkan/react-native-iconify/releases/tag/v0.2.12)

<img src="https://github.com/oktaysenkan/react-native-iconify/assets/42527467/0d74aaed-48c6-4232-b325-3c0f30f73b6d" width="500px" />

**Comment by Doko-Demo-Doa** [comment]
Awesome!
